name: CI

on:
  - push
  - pull_request

jobs:
  Check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: cachix/install-nix-action@v20
        with:
          github_access_token: ${{ secrets.GITHUB_TOKEN }}        
      - name: Run formatter
        run: nix run nixpkgs#nixpkgs-fmt .
      - name: Check for changes
        run: git diff --exit-code
