name: CI

on:
  push:
    branches: [main]
    paths:
      - '.sources/**'
      - '**.lock'
      - '**.nix'
  pull_request:
    paths:
      - '.sources/**'
      - '**.lock'
      - '**.nix'
  workflow_dispatch:

jobs:
  format:
    name: Check formatting
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install Nix
        uses: cachix/install-nix-action@V27

      - name: Run formatter
        run: |
          nix run --inputs-from ./dev nixpkgs#nixpkgs-fmt -- .

      - name: Check for changes
        run: git diff --color=always --exit-code

  vm:
    name: Test Modules
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install Nix
        uses: cachix/install-nix-action@V27

      - name: Setup cache
        uses: DeterminateSystems/magic-nix-cache-action@v6

      - name: Run VM
        run: |
          nix build --print-build-logs --show-trace ./dev#checks.x86_64-linux.module-vm-test
