name: Format

on:
  push:
    branches: [main]
  pull_request:

jobs:
  format-check:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: cachix/install-nix-action@v20
        with:
          github_access_token: ${{ secrets.GITHUB_TOKEN }}
      - name: Run formatter
        run: nix fmt
      - name: Check for changes
        run: git diff --color=always --exit-code
