name: Format

on:
  push:
    branches: [main]
  pull_request:

jobs:
  format-check:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: cachix/install-nix-action@v24

      - name: Run formatter
        run: |
          pushd dev/
          nix fmt
          popd

      - name: Check for changes
        run: git diff --color=always --exit-code
