name: Release

on:
  push:
    branches: [main]

jobs:
  release-please:
    name: Make release
    runs-on: ubuntu-latest

    permissions:
      contents: write
      pull-requests: write

    steps:
      - uses: google-github-actions/release-please-action@v4
        with:
          release-type: simple
          package-name: catppuccin/nix
