name: Test modules

on:
  push:
    paths:
      - 'modules/**'
      - 'test.nix'
      - 'flake.*'
  pull_request:
    paths:
      - 'modules/**'
      - 'test.nix'
      - 'flake.*'
  workflow_dispatch:

jobs:
  run-vm:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: cachix/install-nix-action@v20
      - uses: DeterminateSystems/magic-nix-cache-action@main

      - name: Run VM
        run: nix build .#tests.x86_64-linux.modules
