name: Update flake.lock

on:
  schedule:
    # run every friday
    - cron: "0 0 * * 5"
  workflow_dispatch:

jobs:
  update:
    name: Run update & create PR

    runs-on: ubuntu-latest

    permissions:
      contents: write
      pull-requests: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Nix
        uses: cachix/install-nix-action@V27

      - uses: DeterminateSystems/update-flake-lock@v22
        with:
          path-to-flake-dir: "./dev"
          commit-msg: "chore: update dev flake inputs"
          pr-title: "chore: update dev flake inputs"
          token: ${{ github.token }}
